---
- hosts: server
  become: true
  vars:
    package_list:
      - git
      - pip
      - python
      - java-17
      - httpd
  tasks:
    - name: installation of packages
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{package_list}}"
    - name: httpd service up
      service:
        name: "{{package_list[4]}}"
        state: started

    - name: check the installation
      command: rpm -q git
      register: status
      ignore_errors: yes
    - name: installation
      yum:
        name: git
        state: present
        when: status.rc != 0
    - name: jenkins installation
      get_url:
        repo: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
      yum:
        name: jenkins
        state: present
      service:
        name: jenkins
        state: started
      
        

