---
- hosts: server
  become: true
  vars:
    package_list:
      - git
      - pip
      - python
      - java-17
  tasks:
    - name: installation of packages
      yum:
        name: "{{item}}"
        state: present

      with_items: "{{package_list}}"
