---
- hosts: server
  become: true
  vars:
    package_list:
      - git
      - pip
      - python
      - java-17
      - httpd
  tasks:
    - name: installation of packages
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{package_list}}"
    - name: httpd service up
      service:
        name: "{{package_list[4]}}"
        state: started

    
    - name: jenkins installation
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name:
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
    - name: jenkins install
      yum:
        name: jenkins
        state: present
    - name: jenkins up
      service:
        name: jenkins
        state: started
    - name: directory creation
      file:
         name: /tmp/GIT
         state: directory

    - name: git clone
      git:
        repo: https://github.com/kprasantasg87/Ansible-class.git
        dest: /tmp/GIT
      
        

