---
- hosts: server
  become: true
  vars:
    package_list:
      - git
      - pip
      - python
      - java-17
      - httpd
  tasks:
    - name: installation of packages
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{package_list}}"
    - name: httpd service up
      service:
        name: "{{package_list[4]}}"
        state: started

    - name: check the installation
      command: rpm -q httpd
      register: status
      ignore_errors: yes
    - name: installation
      yum:
        name: httpd 
        state: present
        when: status.rc != 0
