---
- hosts: server
  become: true
  tasks:
    - name: git install
      yum:
        name: httpd 
        state: present
      service:
          name: httpd
          state: started
      
          
      
